# Generated by Django 5.2.14 on 2026-05-20 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BatchInfo',
            fields=[
                ('batchnr', models.IntegerField(primary_key=True, serialize=False)),
                ('orderdate', models.CharField(max_length=32)),
            ],
            options={
                'db_table': 'batchinfo',
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artnr', models.CharField(db_index=True, max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('stock', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'modules',
            },
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch', models.IntegerField()),
                ('artnr', models.CharField(db_index=True, max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('stock', models.IntegerField(blank=True, null=True)),
                ('klass', models.CharField(blank=True, db_column='class', max_length=255, null=True)),
                ('value1', models.CharField(blank=True, max_length=255, null=True)),
                ('value2', models.CharField(blank=True, max_length=255, null=True)),
                ('mark', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'parts',
            },
        ),
        migrations.CreateModel(
            name='PartDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artnr', models.CharField(db_index=True, max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('stock', models.IntegerField(blank=True, null=True)),
                ('klass', models.CharField(blank=True, db_column='class', max_length=255, null=True)),
            ],
            options={
                'db_table': 'partdetails',
            },
        ),
        migrations.CreateModel(
            name='Resistor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_value', models.CharField(db_column='f_value', max_length=64)),
                ('value', models.CharField(max_length=64)),
                ('tolerance', models.CharField(max_length=64)),
                ('comment', models.CharField(blank=True, default='', max_length=255)),
            ],
            options={
                'db_table': 'resistors',
            },
        ),
    ]
